/* Generated By:JavaCC: Do not edit this line. RubyLexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RubyLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RW_PRE_EXEC_BEGIN = 6;
  /** RegularExpression Id. */
  int RW_PRE_EXEC_END = 7;
  /** RegularExpression Id. */
  int RW_ALIAS = 8;
  /** RegularExpression Id. */
  int RW_AND = 9;
  /** RegularExpression Id. */
  int RW_BEGIN = 10;
  /** RegularExpression Id. */
  int RW_BREAK = 11;
  /** RegularExpression Id. */
  int RW_CASE = 12;
  /** RegularExpression Id. */
  int RW_CLASS = 13;
  /** RegularExpression Id. */
  int RW_DEF = 14;
  /** RegularExpression Id. */
  int RW_DEFINED = 15;
  /** RegularExpression Id. */
  int RW_DO = 16;
  /** RegularExpression Id. */
  int RW_ELSE = 17;
  /** RegularExpression Id. */
  int RW_ELSIF = 18;
  /** RegularExpression Id. */
  int RW_END = 19;
  /** RegularExpression Id. */
  int RW_ENSURE = 20;
  /** RegularExpression Id. */
  int RW_FALSE = 21;
  /** RegularExpression Id. */
  int RW_FOR = 22;
  /** RegularExpression Id. */
  int RW_IF = 23;
  /** RegularExpression Id. */
  int RW_IN = 24;
  /** RegularExpression Id. */
  int RW_MODULE = 25;
  /** RegularExpression Id. */
  int RW_NEXT = 26;
  /** RegularExpression Id. */
  int RW_NIL = 27;
  /** RegularExpression Id. */
  int RW_NOT = 28;
  /** RegularExpression Id. */
  int RW_OR = 29;
  /** RegularExpression Id. */
  int RW_REDO = 30;
  /** RegularExpression Id. */
  int RW_RESCUE = 31;
  /** RegularExpression Id. */
  int RW_RETRY = 32;
  /** RegularExpression Id. */
  int RW_RETURN = 33;
  /** RegularExpression Id. */
  int RW_SELF = 34;
  /** RegularExpression Id. */
  int RW_SUPER = 35;
  /** RegularExpression Id. */
  int RW_THEN = 36;
  /** RegularExpression Id. */
  int RW_TRUE = 37;
  /** RegularExpression Id. */
  int RW_UNDEF = 38;
  /** RegularExpression Id. */
  int RW_UNLESS = 39;
  /** RegularExpression Id. */
  int RW_UNTIL = 40;
  /** RegularExpression Id. */
  int RW_WHEN = 41;
  /** RegularExpression Id. */
  int RW_WHILE = 42;
  /** RegularExpression Id. */
  int RW_YIELD = 43;
  /** RegularExpression Id. */
  int LETTER = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int ID_GLOBAL = 46;
  /** RegularExpression Id. */
  int ID_CLASS = 47;
  /** RegularExpression Id. */
  int ID_INSTANCE = 48;
  /** RegularExpression Id. */
  int ID_CONSTANT = 49;
  /** RegularExpression Id. */
  int ID_LOCAL = 50;
  /** RegularExpression Id. */
  int NUM_INT = 51;
  /** RegularExpression Id. */
  int NUM_DEC = 52;
  /** RegularExpression Id. */
  int NUM_HEX = 53;
  /** RegularExpression Id. */
  int NUM_BIN = 54;
  /** RegularExpression Id. */
  int NUM_OCT = 55;
  /** RegularExpression Id. */
  int NUM_CHAR_ASCII = 56;
  /** RegularExpression Id. */
  int STRING_SINGLE = 57;
  /** RegularExpression Id. */
  int STRING_DOUBLE = 58;
  /** RegularExpression Id. */
  int OP_CASE_EQUAL = 59;
  /** RegularExpression Id. */
  int OP_SPACESHIP = 60;
  /** RegularExpression Id. */
  int OP_RANGE_EXC = 61;
  /** RegularExpression Id. */
  int OP_SCOPE = 62;
  /** RegularExpression Id. */
  int OP_EXP = 63;
  /** RegularExpression Id. */
  int OP_RSHIFT = 64;
  /** RegularExpression Id. */
  int OP_LSHIFT = 65;
  /** RegularExpression Id. */
  int OP_PLUS_ASSIGN = 66;
  /** RegularExpression Id. */
  int OP_MINUS_ASSIGN = 67;
  /** RegularExpression Id. */
  int OP_MULT_ASSIGN = 68;
  /** RegularExpression Id. */
  int OP_DIV_ASSIGN = 69;
  /** RegularExpression Id. */
  int OP_MOD_ASSIGN = 70;
  /** RegularExpression Id. */
  int OP_GREATER_EQUAL = 71;
  /** RegularExpression Id. */
  int OP_LESS_EQUAL = 72;
  /** RegularExpression Id. */
  int OP_EQUAL = 73;
  /** RegularExpression Id. */
  int OP_NOT_EQUAL = 74;
  /** RegularExpression Id. */
  int OP_MATCH = 75;
  /** RegularExpression Id. */
  int OP_NOT_MATCH = 76;
  /** RegularExpression Id. */
  int OP_AND = 77;
  /** RegularExpression Id. */
  int OP_OR = 78;
  /** RegularExpression Id. */
  int OP_RANGE_INC = 79;
  /** RegularExpression Id. */
  int OP_PLUS = 80;
  /** RegularExpression Id. */
  int OP_MINUS = 81;
  /** RegularExpression Id. */
  int OP_MULTIPLY = 82;
  /** RegularExpression Id. */
  int OP_DIVIDE = 83;
  /** RegularExpression Id. */
  int OP_MOD = 84;
  /** RegularExpression Id. */
  int OP_BIT_NOT = 85;
  /** RegularExpression Id. */
  int OP_BIT_AND = 86;
  /** RegularExpression Id. */
  int OP_BIT_OR = 87;
  /** RegularExpression Id. */
  int OP_BIT_XOR = 88;
  /** RegularExpression Id. */
  int OP_ASSIGN = 89;
  /** RegularExpression Id. */
  int OP_GREATER = 90;
  /** RegularExpression Id. */
  int OP_LESS = 91;
  /** RegularExpression Id. */
  int OP_NOT = 92;
  /** RegularExpression Id. */
  int OP_LPAREN = 93;
  /** RegularExpression Id. */
  int OP_RPAREN = 94;
  /** RegularExpression Id. */
  int OP_LBRACE = 95;
  /** RegularExpression Id. */
  int OP_RBRACE = 96;
  /** RegularExpression Id. */
  int OP_LBRACKET = 97;
  /** RegularExpression Id. */
  int OP_RBRACKET = 98;
  /** RegularExpression Id. */
  int OP_COMMA = 99;
  /** RegularExpression Id. */
  int OP_DOT = 100;
  /** RegularExpression Id. */
  int OP_COLON = 101;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"BEGIN\"",
    "\"END\"",
    "\"alias\"",
    "\"and\"",
    "\"begin\"",
    "\"break\"",
    "\"case\"",
    "\"class\"",
    "\"def\"",
    "\"defined\"",
    "\"do\"",
    "\"else\"",
    "\"elsif\"",
    "\"end\"",
    "\"ensure\"",
    "\"false\"",
    "\"for\"",
    "\"if\"",
    "\"in\"",
    "\"module\"",
    "\"next\"",
    "\"nil\"",
    "\"not\"",
    "\"or\"",
    "\"redo\"",
    "\"rescue\"",
    "\"retry\"",
    "\"return\"",
    "\"self\"",
    "\"super\"",
    "\"then\"",
    "\"true\"",
    "\"undef\"",
    "\"unless\"",
    "\"until\"",
    "\"when\"",
    "\"while\"",
    "\"yield\"",
    "<LETTER>",
    "<DIGIT>",
    "<ID_GLOBAL>",
    "<ID_CLASS>",
    "<ID_INSTANCE>",
    "<ID_CONSTANT>",
    "<ID_LOCAL>",
    "<NUM_INT>",
    "<NUM_DEC>",
    "<NUM_HEX>",
    "<NUM_BIN>",
    "<NUM_OCT>",
    "<NUM_CHAR_ASCII>",
    "<STRING_SINGLE>",
    "<STRING_DOUBLE>",
    "\"===\"",
    "\"<=>\"",
    "\"...\"",
    "\"::\"",
    "\"**\"",
    "\">>\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"=~\"",
    "\"!~\"",
    "\"&&\"",
    "\"||\"",
    "\"..\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\":\"",
  };

}
