/* RubyLexerTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. RubyLexerTokenManager.java */

/** Token Manager. */
public class RubyLexerTokenManager implements RubyLexerConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xc0L) != 0L)
         {
            jjmatchedKind = 49;
            return 13;
         }
         if ((active0 & 0xfffffffff00L) != 0L)
         {
            jjmatchedKind = 50;
            return 15;
         }
         return -1;
      case 1:
         if ((active0 & 0xc0L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 49;
               jjmatchedPos = 1;
            }
            return 13;
         }
         if ((active0 & 0x21810000L) != 0L)
            return 15;
         if ((active0 & 0xfffde7eff00L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 50;
               jjmatchedPos = 1;
            }
            return 15;
         }
         return -1;
      case 2:
         if ((active0 & 0xfffc6363d00L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 50;
               jjmatchedPos = 2;
            }
            return 15;
         }
         if ((active0 & 0x80L) != 0L)
            return 13;
         if ((active0 & 0x1848c200L) != 0L)
            return 15;
         if ((active0 & 0x40L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 49;
               jjmatchedPos = 2;
            }
            return 13;
         }
         return -1;
      case 3:
         if ((active0 & 0xdcb8234ad00L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 3;
            return 15;
         }
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 3;
            return 13;
         }
         if ((active0 & 0x23444021000L) != 0L)
            return 15;
         return -1;
      case 4:
         if ((active0 & 0x40L) != 0L)
            return 13;
         if ((active0 & 0x8282108000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 4;
            return 15;
         }
         if ((active0 & 0xd4900242d00L) != 0L)
            return 15;
         return -1;
      case 5:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 5;
            return 15;
         }
         if ((active0 & 0x8282100000L) != 0L)
            return 15;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 92;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1400L);
      case 37:
         jjmatchedKind = 84;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x40L);
      case 38:
         jjmatchedKind = 86;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000L);
      case 40:
         return jjStopAtPos(0, 93);
      case 41:
         return jjStopAtPos(0, 94);
      case 42:
         jjmatchedKind = 82;
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x10L);
      case 43:
         jjmatchedKind = 80;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4L);
      case 44:
         return jjStopAtPos(0, 99);
      case 45:
         jjmatchedKind = 81;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L);
      case 46:
         jjmatchedKind = 100;
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x8000L);
      case 47:
         jjmatchedKind = 83;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20L);
      case 58:
         jjmatchedKind = 101;
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x0L);
      case 60:
         jjmatchedKind = 91;
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x102L);
      case 61:
         jjmatchedKind = 89;
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0xa00L);
      case 62:
         jjmatchedKind = 90;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x81L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x40L, 0x0L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x80L, 0x0L);
      case 91:
         return jjStopAtPos(0, 97);
      case 93:
         return jjStopAtPos(0, 98);
      case 94:
         return jjStopAtPos(0, 88);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x300L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0xc00L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1c000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x1e0000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x600000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1800000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x1c000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x3c0000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xc00000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x3000000000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x1c000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x60000000000L, 0x0L);
      case 121:
         return jjMoveStringLiteralDfa1_0(0x80000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 95);
      case 124:
         jjmatchedKind = 87;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000L);
      case 125:
         return jjStopAtPos(0, 96);
      case 126:
         return jjStopAtPos(0, 85);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x2000L) != 0L)
            return jjStopAtPos(1, 77);
         break;
      case 42:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 63);
         break;
      case 46:
         if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000000L, active1, 0L);
      case 58:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(1, 62);
         break;
      case 60:
         if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(1, 65);
         break;
      case 61:
         if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(1, 66);
         else if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(1, 67);
         else if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(1, 68);
         else if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(1, 69);
         else if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(1, 70);
         else if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(1, 71);
         else if ((active1 & 0x100L) != 0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(1, 74);
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000000000000L, active1, 0L);
      case 62:
         if ((active1 & 0x1L) != 0L)
            return jjStopAtPos(1, 64);
         break;
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x40L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x201000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x7c400c400L, active1, 0L);
      case 102:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(1, 23, 15);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x61000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x80008000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x62100L, active1, 0L);
      case 110:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(1, 24, 15);
         return jjMoveStringLiteralDfa2_0(active0, 0x1c000180200L, active1, 0L);
      case 111:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(1, 16, 15);
         return jjMoveStringLiteralDfa2_0(active0, 0x12400000L, active1, 0L);
      case 114:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(1, 29, 15);
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000800L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L, active1, 0L);
      case 124:
         if ((active1 & 0x4000L) != 0L)
            return jjStopAtPos(1, 78);
         break;
      case 126:
         if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(1, 75);
         else if ((active1 & 0x1000L) != 0L)
            return jjStopAtPos(1, 76);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(2, 61);
         break;
      case 61:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStopAtPos(2, 59);
         break;
      case 62:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(2, 60);
         break;
      case 68:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 13);
         break;
      case 71:
         return jjMoveStringLiteralDfa3_0(active0, 0x40L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 100:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 15);
         else if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 19, 15);
         return jjMoveStringLiteralDfa3_0(active0, 0x4042000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0xa1000000800L);
      case 102:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000100L);
      case 108:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(2, 27, 15);
         return jjMoveStringLiteralDfa3_0(active0, 0x8400200000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 114:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(2, 22, 15);
         break;
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x80161000L);
      case 116:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(2, 28, 15);
         return jjMoveStringLiteralDfa3_0(active0, 0x10300000000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x900L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 15);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 15);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 15);
         return jjMoveStringLiteralDfa4_0(active0, 0xc800000000L);
      case 102:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 15);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000048400L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000000000L);
      case 110:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 15);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 41, 15);
         break;
      case 111:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 15);
         break;
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x202000L);
      case 116:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 15);
         break;
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x202100000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 13);
         break;
      case 100:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 43, 15);
         break;
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 15);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 42, 15);
         break;
      case 102:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 18, 15);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 38, 15);
         break;
      case 107:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 15);
         break;
      case 108:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 40, 15);
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 110:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(4, 10, 15);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 114:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(4, 35, 15);
         return jjMoveStringLiteralDfa5_0(active0, 0x200100000L);
      case 115:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 15);
         else if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 13, 15);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 121:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(4, 32, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 20, 15);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 15);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(5, 31, 15);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 110:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 15);
         break;
      case 115:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 39, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 100:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 15, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 51;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                     { jjCheckNAddStates(0, 4); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddStates(5, 7); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(8, 10); }
                  else if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 3;
                  else if (curChar == 35)
                  {
                     if (kind > 5)
                        kind = 5;
                     { jjCheckNAdd(1); }
                  }
                  else if (curChar == 63)
                     jjstateSet[jjnewStateCnt++] = 17;
                  if (curChar == 48)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAdd(1); }
                  break;
               case 2:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 16:
                  if (curChar == 63)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0xfffffffeffffd9ffL & l) != 0L && kind > 56)
                     kind = 56;
                  break;
               case 18:
               case 23:
                  if (curChar == 39)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 19:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 20:
                  if (curChar == 39 && kind > 57)
                     kind = 57;
                  break;
               case 24:
                  if (curChar == 34)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 25:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 27:
                  { jjCheckNAddStates(5, 7); }
                  break;
               case 28:
                  if (curChar == 34 && kind > 58)
                     kind = 58;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  { jjCheckNAddStates(0, 4); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  { jjCheckNAddTwoStates(30, 31); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  { jjCheckNAddTwoStates(31, 32); }
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(14, 16); }
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(17, 19); }
                  break;
               case 36:
                  if (curChar == 46)
                     { jjCheckNAdd(37); }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  { jjCheckNAddStates(20, 22); }
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  { jjCheckNAddStates(23, 25); }
                  break;
               case 41:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(42); }
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  { jjCheckNAddTwoStates(42, 43); }
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 45:
                  if (curChar == 48)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 50:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  { jjCheckNAdd(50); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe80000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     { jjCheckNAdd(15); }
                  }
                  else if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     { jjCheckNAdd(13); }
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 10;
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
               case 4:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  { jjCheckNAdd(4); }
                  break;
               case 5:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  { jjCheckNAdd(7); }
                  break;
               case 8:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 9:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
               case 11:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 48)
                     kind = 48;
                  { jjCheckNAdd(11); }
                  break;
               case 12:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjCheckNAdd(13); }
                  break;
               case 13:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjCheckNAdd(13); }
                  break;
               case 14:
                  if ((0x7fffffe80000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAdd(15); }
                  break;
               case 15:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAdd(15); }
                  break;
               case 17:
                  if ((0xffffffffefffffffL & l) != 0L && kind > 56)
                     kind = 56;
                  break;
               case 19:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 21:
                  if (curChar == 92)
                     { jjAddStates(26, 27); }
                  break;
               case 22:
                  if (curChar == 92)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 25:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 26:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  { jjCheckNAddStates(5, 7); }
                  break;
               case 31:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 38:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 40:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(28, 29); }
                  break;
               case 43:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if ((0x100000001000000L & l) != 0L)
                     { jjCheckNAdd(47); }
                  break;
               case 47:
                  if ((0x7e8000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  { jjCheckNAdd(47); }
                  break;
               case 48:
                  if ((0x400000004L & l) != 0L)
                     { jjCheckNAdd(49); }
                  break;
               case 49:
                  if (curChar != 95)
                     break;
                  if (kind > 54)
                     kind = 54;
                  { jjCheckNAdd(49); }
                  break;
               case 50:
                  if (curChar != 95)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjstateSet[jjnewStateCnt++] = 50;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 17:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 56)
                     kind = 56;
                  break;
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(8, 10); }
                  break;
               case 25:
               case 27:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 51 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\102\105\107\111\116", "\105\116\104", 
"\141\154\151\141\163", "\141\156\144", "\142\145\147\151\156", "\142\162\145\141\153", 
"\143\141\163\145", "\143\154\141\163\163", "\144\145\146", "\144\145\146\151\156\145\144", 
"\144\157", "\145\154\163\145", "\145\154\163\151\146", "\145\156\144", 
"\145\156\163\165\162\145", "\146\141\154\163\145", "\146\157\162", "\151\146", "\151\156", 
"\155\157\144\165\154\145", "\156\145\170\164", "\156\151\154", "\156\157\164", "\157\162", 
"\162\145\144\157", "\162\145\163\143\165\145", "\162\145\164\162\171", 
"\162\145\164\165\162\156", "\163\145\154\146", "\163\165\160\145\162", "\164\150\145\156", 
"\164\162\165\145", "\165\156\144\145\146", "\165\156\154\145\163\163", "\165\156\164\151\154", 
"\167\150\145\156", "\167\150\151\154\145", "\171\151\145\154\144", null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, "\75\75\75", 
"\74\75\76", "\56\56\56", "\72\72", "\52\52", "\76\76", "\74\74", "\53\75", "\55\75", 
"\52\75", "\57\75", "\45\75", "\76\75", "\74\75", "\75\75", "\41\75", "\75\176", 
"\41\176", "\46\46", "\174\174", "\56\56", "\53", "\55", "\52", "\57", "\45", "\176", 
"\46", "\174", "\136", "\75", "\76", "\74", "\41", "\50", "\51", "\173", "\175", 
"\133", "\135", "\54", "\56", "\72", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   30, 31, 33, 34, 36, 25, 26, 28, 19, 20, 21, 46, 48, 50, 33, 34, 
   36, 34, 35, 36, 37, 38, 40, 38, 39, 40, 22, 23, 41, 42, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public RubyLexerTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public RubyLexerTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 51; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, 
};
static final long[] jjtoToken = {
   0xffffcfffffffffc1L, 0x3fffffffffL, 
};
static final long[] jjtoSkip = {
   0x3eL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[51];
    private final int[] jjstateSet = new int[2 * 51];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
